mozilla/thimble.mozilla.org

public/stylesheets/userbar-overrides.less

see also  https://github.com/mozilla/webmaker-login-ux/issues/118

Use pointer cursor for log out button

---

views/layout.html

I'm working on making our Brackets/Thimble smaller, and there are a bunch of things that we can do just to Thimble.  This is the first, and it's a pretty easy fix.

Use minified CSS/JS resources from CDNs

---

routes/index.js

Added functionality which upon language change in thimble adds the locale code to Backet's query string. Addresses #504.

Issue504 locale

---

public/friendlycode/js/fc/bramble-ui-bridge.js
views/friendlycode/templates/nav-options.html

Preview mode and themes are now changed on load.

Linked bramble API to initial state

---

public/friendlycode/css/editor.less
public/stylesheets/userbar.less

Improved visuals of user dropdown and cog dropdown. Removed stark bordering and ineffective shadowing, replaced with the same shadowing used by brackets.

Brought thimble dropdowns in line with brackets right click modals

---

public/friendlycode/js/fc/bramble-ui-bridge.js
public/stylesheets/publish.less
public/stylesheets/userbar.less
views/index.html
views/layout.html
views/publish.html
views/userbar.html

Complete publish dialog, ready to be connected with backend functionality.

Added publish dialog

---

public/friendlycode/js/fc/filesystem-sync.js
public/friendlycode/js/fc/load-project-files.js
public/scripts/open-project.js
routes/create-or-update-file.js
routes/delete-file.js
routes/utils.js

Show the last modified date for a project and update the last modified date on every file change

Show last modified

---

public/scripts/open-project.js

Add separate requirejs config for open-projects.js

---

app.js
env.dist
lib/middleware.js
package.json
public/scripts/editor/js/fc/filesystem-sync.js
public/scripts/editor/js/fc/load-project-files.js
routes/create-or-update-file.js

This is a WIP, since I can't get the full dev environment working locally.

Fix #626: add support for multipart uploads

---

public/scripts/editor/js/fc/publisher.js
public/stylesheets/publish.less
views/publish.html

Whoever reviews this, please also test it, since I can't get publish working locally atm.

Fix #708: remove 'Show in public gallery' toggle from the Publish dialog

---

package.json
routes/create-or-update-file.js

Followup to #722.
Sister patch in publish is here: https://github.com/mozilla/publish.webmaker.org/pull/119/files

Use multipart uploads from Thimble to Publish

---

app.js
public/resources/tutorial/tutorial.css
routes/index.js
routes/tutorial.js
views/tutorial-style-guide.html
views/tutorial-template.html

This isn't working yet, I get:
```
500: TypeError: Cannot assign to read only property '_locals' of http://localhost:3500
Please try a search or visit our homepage.
```

Add tutorial resources to Thimble, part of #737

---

public/img/icon/plus-white.svg
public/scripts/editor/js/fc/bramble-keyhandler.js
public/scripts/editor/js/fc/bramble-menus.js
public/scripts/editor/js/fc/bramble-popupmenu.js
public/scripts/editor/js/fc/bramble-ui-bridge.js
public/scripts/editor/js/fc/bramble-underlay.js
public/scripts/editor/js/fc/filesystem-sync.js
public/stylesheets/editor.less
views/nav-options.html
views/publish.html

This builds on the changes in https://github.com/humphd/brackets/pull/397

Issue723 UX

---

views/projects.html

Fixed #769 - Removed dead remix link from projects page

---

default/stay-calm/tutorial.html

This patch greatly simplifies showing the correct styling in the Keep Calm sample make's tutorial.

Fixed #760 - Inlined default tutorial css

---

public/scripts/editor/js/bramble-editor.js
public/scripts/editor/js/fc/load-project-files.js

This reverts commit f7171349f14a6276cb59bd51cb9c5707c913e02b.

Revert "Fix #768 - Use symlinks for project roots"

---

app.js
public/scripts/sso-override.js
routes/config.js
routes/home.js
routes/index.js
routes/login.js
views/publish.html
views/userbar.html

This will help with implementing the anon workflow

Add login route to thimble

---

public/scripts/editor/js/bramble-editor.js
public/scripts/editor/js/fc/close-warning.js
public/scripts/editor/js/fc/publisher.js

Untested!  Let me know if this works :)

Fix #763: Add warning if there is unsaved work when user closes Thimble

---

public/stylesheets/editor.less
public/stylesheets/userbar.less

@flukeout, I'm not sure if I've done what you want for the 2nd bit about the "active" state on the menu, can you review this please?

Fix #805 - Change green in the header to match homepage

---

routes/remix.js

Relies on mozilla/publish.webmaker.org#136 landing

Offload remix logic(copying projects) onto publish.webmaker.org for authenticated users

---

public/resources/remix/index.js
public/resources/remix/style.less

I *think* this is right, but I'm not an expert on jquery.  From my research, this seems to be the way they want you to go.
I've also bumped up the z-index on the remix details.

Fix #826 - Project metadata and Remix not showing up

---

public/scripts/editor/js/bramble-editor.js
public/scripts/editor/js/fc/bramble-ui-bridge.js
public/scripts/editor/js/fc/filesystem-sync.js
public/scripts/project/metadata.js

This seems to work like I want, but I see some issues with `Saving...` never going away, and I wonder if what I'm doing in the callbacks for `handleFileRename` are right.

Add rename handling, fix lock callbacks for error cases

---

public/scripts/editor/js/fc/bramble-ui-bridge.js
views/userbar.html

@flukeout still needs to get me a proper icon (I reused the sign-out one), but this works perfectly.

Fix #824: Add UI for calling bramble.export()

---

app.js
lib/middleware.js
package.json
public/scripts/constants.js
public/scripts/editor/js/bramble-editor.js
public/scripts/editor/js/fc/bramble-ui-bridge.js
public/scripts/editor/js/fc/filesystem-sync.js
public/scripts/editor/js/fc/project-rename.js
public/scripts/editor/js/fc/publisher.js
public/scripts/main.js
public/scripts/project/metadata.js
public/scripts/project/project.js
public/scripts/project/remote.js
public/scripts/sso-override.js
routes/get-file-contents.js
routes/get-file-metadata.js
routes/home.js
routes/index.js
routes/login.js
routes/main.js
routes/remix.js
routes/root.js
routes/utils.js
views/bramble.html

Client-side and Server-side fixes for upgrading a project when you sign in

---

public/stylesheets/colors.less
public/stylesheets/editor.less
views/nav-options.html

Minor adjustments to icon positioning, size as well as hover & active states.
Work is related to #868

Editor title bar UI cleanup

---

public/scripts/editor/js/fc/bramble-ui-bridge.js
public/stylesheets/editor.less
views/nav-options.html

Some minor updates to the Preview Bar
* Moved refresh icon to the right side of the preview bar
* Added different styles to the Preview and Tutorial toggle
* Selected option is only underlined when there are two options
* White background on the mobile & desktop toggle to match the refresh icon
Part of the effort outlined in #868

Preview bar updates

---

public/stylesheets/userbar.less

Changes
* Updated Publish button styling and hover/active states
* Updated rename Save button styling and hover/active states
* Font size in the project rename input field now same as non-editable project name font size
* Removed style transitions from UI elements
* Added hover & active states to the Thimble logo
* Updated position of the rename project pencil icon
Continuation of work in #868

Style updates to the green header bar

---

public/img/icon/minus-white.svg
public/scripts/editor/js/fc/bramble-menus.js
public/stylesheets/editor.less
views/nav-options.html

Updates to the gear menu
* Centered the Plus and Minus icons inside the green buttons
* Cleaned up Theme toggle styles
* Replaced "+" and "-" in the font size icons with SVG images

Editor options menu updates

---

public/stylesheets/editor.less

**Changes**
* Removed extra spacing above the Upload... option
* Changed the harsh green hover states with a lighter grey
Continued work from #868

Add file menu updates

---

public/scripts/editor/js/fc/bramble-popupmenu.js
public/stylesheets/editor.less

**Changes**
* Added hover and active states to the increase and decrease font size buttons
* Centered the Add File & Editor Options menu under the icons when they're opened
* Removed the fade in & out effect from the menus opening and closing

More UI adjustments

---

public/scripts/editor/js/fc/bramble-ui-bridge.js
public/stylesheets/userbar.less
views/userbar.html

Changes, when not signed in...
* Copy now says "Log In or Sign Up to Save or [Publish]" in a sentence-like structure
* When the Publish button is pressed, the Log In and Sign Up sentence is strobed for emphasis
Continuation of work in #868

Updates to the behaviour and styling of the Log In area.

---

public/stylesheets/publish.less
views/publish.html

**Changes**
* Updated button styling on Publish and Cancel buttons
* Hover & active states
* Colors
* Rounded corners
* Updated styling on Description field and label
* Darker background on Cancel and Publish button area for emphasis
Round 2 to come later when I can publish locally again.
Continuation of work in #868

UI cleanup on Publish Dialog, round 1

---

public/stylesheets/projects-style.css

This gets rid of the always-on scrollbar. Each pane has their own scroll behaviour so this shouldn't be a problem.
To test:
* Load up the editor
* There is no scrollbar along the right side of the screen
* There was before

Small fix for scroll bug

---

views/nav-options.html
views/userbar.html

Added tooltips to a bunch of the UI elements to help explain what they do.

Tooltips for buttons & icons

---

public/scripts/editor/js/fc/bramble-menus.js

I changed it so that the transition speed is set with one variable and sped it up to 200ms.

Sped up the theme toggle UI element

---

public/img/icon/garbage-can-bottom.svg
public/img/icon/garbage-can-top.svg
public/scripts/open-project.js
public/stylesheets/projects-style.css
views/projects.html

**Changes**
* Updated styling on the Project table hover states
* Updated "Create New" button styling, including hover and active states
* Updated Delete icon and hover state
* Some general styling and layout updates
* Rewrote the markup a little and adjusted the delete code accordingly

Your Projects page updates

---

public/stylesheets/userbar.less

**Changes**
* Items in the dropdown menu are the same height as the Add File menu items
* The entire item is clickable in the user dropdown menu, not just the text and icon
* Slight position change on the user dropdown 
Fixes #891

User dropdown menu styling updatees

---

public/stylesheets/editor.less
public/stylesheets/userbar.less

**Changes**
* Added a bolder version of Open Sans for the column headings (Files, Editor, etc.)
* Added a minimum width to all of the column headings so that the icons and UI doesn't jump to the line below (it gets cut off instead)
* Adjusted the font color for the column headings to compensate for their new boldness

Styling updates to the column headers

---

public/scripts/open-project.js

This improves things, I think.

Part of #848 - don't allow a second click after a delete has started

---

public/stylesheets/editor.less
public/stylesheets/publish.less
views/nav-options.html
views/publish.html

**Changes**
* Updated some spacing & padding in the publish dialog
* Made the publish dialog wider to accomodate our URLs
* Updated the button styling in the publish dialog
* Gave the Editor Options gear icon a bigger click area

Styling updates

---

public/resources/default-files/css.txt
public/resources/default-files/html.txt
public/resources/default-files/js.txt
public/scripts/editor/js/fc/bramble-menus.js

Watching my user testing videos, it became clear that when adding new files, providing something to start with would be nice vs. a totally blank page.  Depends on https://github.com/humphd/brackets/pull/444

Add default HTML, CSS, and JS files, use updated bramble.addNewFile()

---

public/stylesheets/projects-style.css
views/projects.html

Made the projects list scroll when there are lots of items.

---

public/homepage/scripts/google-analytics.js
views/editor/layout.html
views/homepage/index.html

Related to https://github.com/mozilla/thimble.webmaker.org/issues/749 and https://github.com/MozillaFoundation/plan/issues/542#issuecomment-135829652
We still need the env updated for the right GA account.

Add Google Analytics to homepage

---

public/google3479be6196d04fac.html

I had the wrong content in the verification file.

Updated verification file

---

public/homepage/stylesheets/style.less

Updating Github footer icon and aligning footer links evenly

---

public/homepage/stylesheets/style.less
views/homepage/index.html

**Changes**
* More distinct hover state
* Tweaked and sped up the pencil animation

Updated Create New Project button styles

---

public/homepage/stylesheets/style.less

Made the footer render consistently between Firefox and Chrome.
Fixes #998

Footer style updates - Fixes #998

---

public/editor/scripts/editor/js/fc/bramble-ui-bridge.js

Fix for the bug where the File tray header is not appearing in Safari

---

public/editor/scripts/editor/js/fc/bramble-menus.js
public/editor/stylesheets/editor.less
public/editor/stylesheets/projects-style.css
public/homepage/stylesheets/style.less
public/homepage/stylesheets/variables.less
public/resources/stylesheets/userbar.less
views/editor/bramble.html
views/editor/nav-options.html

A bunch of fixes for Safari
* Fixes #664 - Fixes layout of editor settings popup 
* Fixes #1062 - Adds strobe effect when clicking Publish and not signed in
* Fixes #1059 - Adds garbage can animation on My Projects page
* Fixes #1061 - Added hover effect to starter projects
* Fixed the New Project button animation on the homepage

Styling fixes for Safari

---

README.md

update id.webamker.org test data

---

README.md

add grunt build-browser step to section on starting brackets/bramble

---

public/editor/scripts/project/remote.js

Fix #1060 - deal with browsers not supporting String.prototype.endsWith()

---

README.md

from https://github.com/mozilla/id.webmaker.org/issues/390#issuecomment-140748446

Fix documentation to match new db schema

---

public/editor/scripts/editor/js/fc/bramble-keyhandler.js
public/editor/scripts/editor/js/fc/bramble-menus.js
public/editor/scripts/editor/js/fc/bramble-popupmenu.js
public/homepage/scripts/main.js
public/homepage/stylesheets/style.less
public/resources/stylesheets/userbar.less
views/editor/userbar.html

This re-uses our PopupMenu code to have the usermenu work like the rest of our popup menus (esc key closes, clicking outside it closes).

Fix #1138, #817 - user menu should open when clicked vs hovered.

---

public/homepage/stylesheets/style.less
public/resources/img/footer-icon-privacy.svg
public/resources/img/footer-icon-terms.svg
views/homepage/index.html

**Changes**
* Added Terms of Use link
* Added Privacy Policy link
* Changed layout to match new X-Ray Goggles site footer
Fixes #696

Footer updates

---

public/editor/scripts/editor/js/fc/bramble-menus.js
public/editor/stylesheets/editor.less
views/editor/nav-options.html

This builds on what @flukeout did in https://github.com/mozilla/thimble.webmaker.org/pull/1166 and connects the UI to the Bramble API.

Fix #648 - add UI for word wrap toggle

---

public/editor/scripts/editor/js/fc/sync-manager.js

This will skip the AJAX delete step if we don't yet have a file id from the server for a given path, indicating that it only exists locally at this point.
r? @gideonthomas

Fix #1207 - don't fail forever when a file rename hasn't created the original file on the server yet.

---

README.md
env.dist
invalidate.js
package.json

Fixed #1132 - Added script to invalidate CloudFront edge caches

---

public/editor/scripts/open-project.js
public/homepage/scripts/main.js
views/homepage/index.html

I did the same idea on the homepage too, and also cleaned up that code a bit.

Fix #753 - give feedback when working to create new projects

---

README.md

Quick patch for a small detail.

Fixed an instruction in the README

---

Gruntfile.js
bower.json
public/editor/scripts/editor/js/fc/bramble-menus.js
public/editor/scripts/editor/js/fc/bramble-ui-bridge.js
public/editor/scripts/editor/js/fc/project-rename.js
public/editor/scripts/google-analytics.js
public/editor/scripts/main.js
public/editor/scripts/open-project.js
public/homepage/scripts/google-analytics.js
public/homepage/scripts/main.js

This adds the Webmaker Analytics client library, and instruments the UI to track a bunch of user actions with custom GA events.  We can easily add more.

Fix #653 - Instrument Thimble, add custom GA Events for user actions

---

Gruntfile.js
app.js
public/editor/scripts/editor/js/bramble-editor.js
public/editor/scripts/editor/js/fc/bramble-ui-bridge.js
public/editor/scripts/editor/js/fc/filesystem-sync.js
public/editor/scripts/editor/js/fc/project-rename.js
public/editor/scripts/editor/js/fc/publisher.js
public/editor/scripts/editor/js/fc/sync-manager.js
public/editor/scripts/main.js
public/editor/scripts/project/project.js
public/editor/scripts/sso-override.js
routes/main/editor.js
views/editor/bramble.html

This patch:
* Combines homepage JS resources into one file and
* Makes our server follow a common requirejs optimization pattern, sharing resources in a more transparent way between the `homepage` and `editor` frontend modules.

Fix #1041 - Bundle homepage javascript files and unify build system

---

public/resources/remix/close-x.svg
public/resources/remix/index.js
public/resources/remix/style.less

Updated Details Bar to match latest designs

---

public/resources/remix/index.js

What is a FOUC you ask? It's a "Flash of unstyled content", and it is very ugly.
Fixes #752 
@humphd R?

Hides the bar markup until the page is fully loaded to avoid a FOUC

---

public/editor/scripts/project-list.js
public/editor/stylesheets/editor.less
public/editor/stylesheets/projects-style.css
public/homepage/stylesheets/style.less
public/resources/stylesheets/userbar.less
routes/projects/read.js
views/editor/index.html
views/editor/layout.html
views/editor/projects.html
views/homepage/userbar.html

Added green header to My Projects page

---

public/resources/remix/style.less

@humphd or @gideonthomas R?
Fixes #1300

Emergency z-index fix for the remix bar. 999 oughtta do it!

---

public/resources/remix/index.js

Fixed Remix button not showing in Safari.

---

public/resources/remix/style.less

Moved the remix button to the bottom right for touch mode...
Changed position and method for dismissing the expanded popup...

Changed the remix button position for touch mode.

---

routes/projects/create.js
routes/projects/index.js
views/editor/projects.html
views/editor/userbar.html
views/homepage/index.html
views/homepage/userbar.html

@flukeout, when you get a sec, can you r?

Fix #1226 - Make "New Project" a real link

---

package.json

Fix #1378 - Update nunjucks to v2.3.0

---

constants.js
env.dist
locales/en-US/messages.properties
public/editor/scripts/editor/js/fc/bramble-ui-bridge.js
public/editor/scripts/project-list.js
public/homepage/scripts/main.js
scripts/properties2json.js
server/lib/middleware.js
server/localize.js
server/routes/auth/login.js
server/routes/auth/oauth2-callback.js
server/routes/main/anonymous.js
server/routes/main/editor.js
server/routes/main/homepage.js
server/routes/main/root.js
server/routes/projects/create.js
server/routes/projects/read.js
server/routes/projects/remix.js
views/editor/bramble.html
views/editor/layout.html
views/editor/projects.html
views/editor/userbar.html
views/homepage/index.html
views/homepage/userbar.html

L10N for: 
* Forcing the url to have the locale
* Rewriting the hrefs and srcs to have the locale in them

L10N for the routes

---

locales/en-US/messages.properties

@kristinashu does this look good?

Fix #1367 - Update sign in wording

---

views/editor/bramble.html

Escape html entities in rendered error messages

---

server/security.js
views/editor/layout.html
views/homepage/index.html

Enable Pontoon for l10n

---

.travis.yml
package.json

specify node version to 4.3.x

---

LICENSE
package.json

Add license and update package.json

---

package.json
server/lib/middleware.js
server/localize.js
server/security.js

This also converts the `middleware.js` file to ES6.

Enable CORS api and allow routes to not be localized

---

locales/en-US/messages.properties
public/resources/stylesheets/userbar.less
views/editor/userbar.html

Fix #1415 - Combine anonymous publish text to enable context based l10n

---

env.dist
locales/en-US/messages.properties
package.json
public/resources/remix/index.js
server/index.js
server/routes/config.js
server/routes/projects/index.js
server/routes/projects/remix-bar.js
views/project-remix-bar.html

I don't yet have a fully functional dev env locally, so I'd appreciate an end-to-end test of this with the publish server.  However, what I have run seems to be working well.
Let me know too if I've done what you want with the string properties.

Fix #1388 - localize the injected project remix header bar and script

---

scripts/localize-client.js
scripts/watch-client.js

Fix client watching script to not crash on changing a non-js file

---

locales/en-US/editor.properties

This adds the strings that were meant to be in the Brackets repo so that Pontoon can access it.

Add Brackets' strings

---

public/homepage/scripts/main.js
server/index.js
server/security.js

Fixes a bunch of CSP errors that pop up so that the console is a bit cleaner

Fix other CSP errors

---

public/resources/stylesheets/userbar.less
views/editor/userbar.html
views/homepage/userbar.html

We're going to disable this for now until we figure out the onboarding process for new languages
@flukeout r?

Remove link to "Add new language" in language-picker

---

views/layout.html

closes https://github.com/MozillaFoundation/mofo-devops/issues/352

Modify deprecation warning on Thimble

---

public/resources/stylesheets/userbar.less

@gideonthomas Can you have a look at this. Thank you :)

text cursor instead of pointer for "sign in" and "create new account"

---

locales/az/messages.properties
locales/cs/messages.properties
locales/de/messages.properties
locales/dsb/messages.properties
locales/en-US/messages.properties
locales/es-CL/messages.properties
locales/es/messages.properties
locales/fr/messages.properties
locales/hsb/messages.properties
locales/hu/messages.properties
locales/nl/messages.properties
locales/pt-BR/messages.properties
locales/pt-PT/messages.properties
locales/ru/messages.properties
locales/sv-SE/messages.properties
locales/tr/messages.properties
locales/uk/messages.properties
locales/zh-CN/messages.properties
locales/zh-TW/messages.properties

Update footer link

---

README.md

Added Chat with the team part

---

default/empty-project/index.html

Refer to : https://github.com/mozilla/thimble.mozilla.org/pull/1663#issuecomment-276567176

Fixed indentation

---

public/resources/default-files/html.txt

Refer to : https://github.com/mozilla/thimble.mozilla.org/pull/1689#issuecomment-276731143

Removed link tag

---

README.md

While installing Thimble, I ran into some installation problems. I didn't know if Bramble was required or not (Since it only mentions needing it if you plan to install it locally).
I've updated the instructions. Hopefully is more clear :)
I've removed the Bramble installation part since the Bramble repository has a really good, in-depth installation instruction. 
Is there anything you would like me to add/remove?

[WIP]Updated installation instructions

---

locales/en-US/messages.properties

I managed to change the text for the confirm delete project button

Fix #1001: Changed text for deleteProjectConfirmText

---

public/resources/tutorial/tutorial.css
server/localize.js

Hey,
In tutorial.css I added a img property and set the max width to 100% of the container size, this should stop images from being wider than the tutorial container.
img{
max-width: 100%;
}

Tutorial.css max width #1229

---

locales/en-GB/messages.properties
locales/en-US/messages.properties
public/editor/scripts/editor/js/fc/bramble-ui-bridge.js
public/editor/stylesheets/editor.less
public/resources/img/icon/file-white.svg
views/editor/nav-options.html
views/editor/userbar.html

Still needs approval and still needs to change the icon :)
As title says, WIP
PS: Also, I'm thinking of changing the export id from "export-project-zip" to "filetree-pane-nav-export-project-zip". If I do that, I'll have to modify bramble-ui-bridge.js too

[WIP]Added export to .zip when not logged in (#981)

---

scripts/setup-services.sh

Here are the changes as described in #1729

Fix Issue#1729

---

default/index.js

Handle presence of files in the default project

---

.gitignore

Adding rules to .gitignore to ignore swap/temp/tag files generated by vim

Gitignore vim files

---

public/editor/stylesheets/editor.less

fixed collapsing nav items when tutorial is added

---

public/resources/remix/style.less

I modified the style.less file by doing these things:
changed the background color to ghostwhite (trying to make it not blend in with a white background)
I increased the box shadow by 10 px instead of its original 2px (To have a shadow at the top)
Added a border 1px with the color gainsboro (To help avoid the bleeding effect)
and  when collapsed that there is no border  (So no border would show over the Remix button till hovered over)
Here is what it looks like with my changes
@humphd  If there is anything you would like me to change please let me know

Moddified style.less to fix Issue # 1334

---

public/editor/stylesheets/editor.less

Color changes to dark grey when we hover over AUTO refresh button.

Add hover effect to the AUTO refresh UI in the preview

---

public/editor/scripts/project-list.js
public/editor/stylesheets/projects-style.less
public/resources/img/icon/star-off.svg
public/resources/img/icon/star-on.svg
public/resources/remix/style.less
views/editor/projects.html

I was able to get a local storage solution for favouriting projects working using the guidance you guys provided. At the moment the project list won't update until the page is refreshed like you specified. I also used the check mark icons in the resources as a placeholder for the project favorite button in case you guys have some better styling that can be used.
I was also having some trouble understanding the syntax used to fill in the text for the title of the <div> using: `title="{{ gettext("prjListDeleteProjectBtnTitle") }}"` so I didn't include a title for the project-favorite button. I was also of thinking of adding some logic to remove a project from the favorites array when it is deleted as well.

Adding local storage project favorites

---

locales/en-US/messages.properties
public/editor/scripts/project-list.js
public/editor/stylesheets/projects-style.less
views/editor/projects.html

**Changes**
* Added small animation to the star icon when it's turned on
* Updated text styling
* Markup & style cleanup
* Hiding description element when it's empty
* Added Published Url when available
* Hiding the list until the projects have been sorted by favorites to avoid the jarring change
* Added a little bit of responsive styling 
**Now looks like...**
Fixes #1774 
Fixes #1626

Updated styling for Your Projects page

---

README.md

Fixes #1782.
Let me know if the text needs to change. :smiley:

Added direct link to Thimble channel on Mattermost instance. Fixes #1782

---

public/editor/scripts/editor/js/fc/publisher.js

Fix #1738 - `callback` is not a function when showing "Update Published Project" prompt

---

public/resources/stylesheets/userbar.less

Fixes #1780 
Removed homepage class in css

Modified userbar.less file

---

package.json

Hello, I am making a fix to the issue #1715 .
This should solve the problem. If there are any problems with this, please let me know so I can fix it later.

Issue 1715

---

.jshintrc

In reference to the issue #1830

Updates .jshintrc, Removes duplicate entry for indent

---

public/editor/stylesheets/editor.less

Fixes #1754 
Changed the value of top as suggested by @flukeout

Changed the CSS for editor dropdown

---

CONTRIBUTING.md

Once this lands, we can remove the corresponding Wiki Page

Contributing guidelines based on current WIKI page

---

public/editor/scripts/editor/js/fc/bramble-ui-bridge.js

Hey!
Changed FadeIn()/Fadeout() to .show()/.hide()
Let me know if everything is good:) A thank you to @humphd for the help, pretty much 100% of the 
answer.

Issue 1634 - Make "menu appears" transition consistent

---

README.md

Fixes #1793. This tells people the proper way to create an account locally

Issue #1793 Edited the Readme file on the correct way to create an account locally

---

locales/en-US/messages.properties
public/editor/stylesheets/editor.less
public/editor/stylesheets/projects-style.less
public/editor/stylesheets/publish.less
public/homepage/stylesheets/gallery.less
public/homepage/stylesheets/style.less
public/resources/stylesheets/userbar.less
views/editor/index.html
views/editor/layout.html
views/editor/publish.html
views/gallery.html
views/homepage/index.html

Lots of changes here, I'll highlight a few
* Removed Fira entirely and moved everything to Open Sans
* Less stuff to load, yey!
* Bumped the default font-weight for Open Sans to 400
* 300 was too faint, this should help overall legibility
* Updated styling for the Publish dialog
* Mostly just tweaked hierarchy and link styling
* Moved "Update Published" section above the link
* Removed duplicate stylesheet link from Editor

Site-wide font changes & updated styling for Publish dialog

---

README.md

Heading were earlier displayed as ####something, changed to

Fix broken headings in readme

---

locales/en-GB/messages.properties
locales/en-US/messages.properties
public/editor/scripts/editor/js/fc/bramble-popupmenu.js
public/editor/stylesheets/editor.less
views/editor/nav-options.html

Fixes #1824. 
Also replaces the labels of menu elements.

Fixes the issue of popup window overflowing to the left side

---

public/editor/scripts/editor/js/fc/project-rename.js

Fixes #1868 
Continuation of #719

Fixes Issue #1868 - Renaming project to same title as previous still shows publish changes prompt

---

public/resources/stylesheets/userbar.less

@flukeout 👍 Fixed the black text bug. I also reviewed my first commit and changed the spacing problem as well. I remember having a lot of problem with my first bug fix with spacing issues. 
And you were completely right about looking at the entire navbar element. 💯 
My approach to this solution was little off. I am glad you were able to help. 
Thank you 😄

Fix: Issue 1912 - Changed black text colour around "sign in" and "create account" link to original white colour with opacity of 0.65 

---

package.json

I have updated the fs-writefile-promise dependency
I tested using "npm install" and all seems to work fine from my end

Fix #1908: Issue 1908 fs-writefile-promise update

---

package.json

I have updated the grunt-contrib-csslint dependency
I tested using "npm install" and all seems to work fine from my end

Fix #1908: Issue 1908 grunt-contrib-csslint update

---

public/homepage/stylesheets/gallery.less

No huge changes here, just some minor styling cleanup:
* Removed borders from activities
* Changed placeholder activities while loading to have a white background
* Added ``:active`` treatment to Remix button & changed Lesson Plan link styling
* Changed treatment of the activity author type
* Made the tags a bit smaller on the activity cards

Minor styling updates to the homepage gallery

---

public/editor/scripts/editor/js/fc/bramble-popupmenu.js
public/editor/stylesheets/editor.less

Added the activate class to element self._button @flukeout

added active class to self._button$ element

---

public/editor/scripts/project-list.js

Fix #1985 - Use correct analytics path for projects list

---

package.json

I have updated the wolfy87-eventemitter dependency
I tested using "npm install" and all seems to work fine from my end 

Fix #1908: Issue 1908 wolfy87-eventemitter update

---

package.json

I have updated the helmet dependency
I tested using "npm install" and all seems to work fine from my end

Fix #1908: Issue 1908 helmet update

---

locales/en-US/editor.properties

Regarding that for localazation: https://github.com/mozilla/brackets/pull/635

Added an error message string for archive max size limit.

---

public/editor/stylesheets/publish.less

Modified padding and removed line-height for the publish-link.
Fixes #1988

Fixing line Height is too small - Issue #1988

---

public/resources/remix/index.js

Fixes #1327 
Changed jQuery dependent code to plain JS code and used DOM methods in some places

fix: Remove jQuery dependency from injected remix button code

---

public/homepage/scripts/gallery.js

Moved from https://github.com/mozilla/thimble.mozilla.org/pull/2027

Remix gallery

---

package.json

I have updated the cryptr dependency 
I tested using "npm install" and all seems to work fine from my end 

Fix #1908: Issue 1908 cryptr update

---

locales/en-US/messages.properties
public/editor/scripts/main.js
public/editor/stylesheets/editor.less
public/resources/stylesheets/userbar.less
views/editor/bramble.html
views/editor/index.html
views/editor/warnings.html

Should look like this if all goes well...
Fixes #1930
cc @humphd

Fix #1930, #2043: Added an alert to prompt the user to refresh Thimble.

---

locales/en-US/editor.properties

Looks like we missed adding these to Thimble when we landed the Brackets portion.

Add l10n strings for Brackets Console

---

locales/en-US/messages.properties
views/homepage/get-involved.html

* Fixed ``&mdash;`` showing up in the text on the Get Involved
* Fixed spacing typos around em-dashes in the copy
Fixes #2085

String Fixes

---

locales/en-US/messages.properties
views/editor/userbar.html

Should appear like this...
Fixes #2076

Added tooltip hover text to Thimble logo in editor

---

public/resources/default-files/css.txt
public/resources/default-files/html.txt
public/resources/default-files/js.txt

Updated the text formatting in the comments as well.
Fixes #2079
Fixes #2078

Updated the default files to match the starting project files. fixes #2079

---

public/homepage/stylesheets/style.less
views/footer.html

Logo should appear like this now across all browsers...
Fixes #2083
I tested via Browser Stack

Changed logo markup to fix IE styling issue.

---

public/editor/scripts/project-list.js
views/editor/projects.html

Fixes #2129
Whatever this code was before, it was terrible. It should be working now.

Fix #2129 - Fix link to remix your own project

---

server/lib/middleware.js

This adds a fallback instance of Cryptr, using the 1.0.0 `eas-256` algorithm

test cryptr fallback  with eas-256

---

public/homepage/scripts/gallery.js

The title wasn't being picked up properly for GA events because the selector was wrong.
Fixes #2165

Fixes missing GA label, had the wrong selector.

---

views/footer.html

Follow up of #2096, missed those links in the footer

Broken links in footer for some locales

---

locales/en-US/editor.properties

This was noticed by @TonnesM in https://github.com/mozilla/thimble.mozilla.org/pull/2176#issuecomment-303520433.

Fix typo, add comment for CONSOLE_HELPTEXT

---

locales/en-US/messages.properties
server/lib/snippets.js

Fix:2143 Modified comment for the style tag

---

public/editor/scripts/main.js

Also updated the Green Screen error description.
Fixes #2190

The Black Screen of Doom now fires off a Google Analytics event we can keep track of.

---

views/editor/bramble.html

Appears on the green loading screen, like this...

Added warning message to loading screen.

---

locales/en-US/editor.properties

Fix:2233 Added localization of file delete dialog

---

public/editor/scripts/project/remote.js

This reuses the same logic we have when we extract tarballs--we forgot to check if there are pending sync operations on files.

Fix #2315 - skip loading files that have pending syncs

---

public/editor/scripts/project/project.js

Fix #2327 - Sync auto-added index.html to server

---

locales/en-US/editor.properties

We have 3 features landing in Brackets today that need new strings.  I've combined them into one PR here in Thimble.
@flukeout fyi, I modified a few small things when doing this.

Add new strings for Project Size UI, Video Viewer, and Font Viewer features

---

views/editor/layout.html
views/editor/userbar.html

Sets target as self for userbar links, Fixes #2123

---

CONTRIBUTING.md

Clarify issue references across repositories in Contributing Guide

---

locales/en-US/editor.properties

We no longer use this string in the Font Viewer, so let's remove it.

Removing unused Font Type label

---

locales/en-US/editor.properties

Added localization strings for the Binary Viewer, which is an in-progress PR...
* https://github.com/mozilla/brackets/pull/851

Strings for new binary viewer

---

views/error.html
views/footer.html
views/homepage/base.html
views/sign-out.html

Fixes#2470: Updates Twitter account to @codewiththimble

---

locales/en-US/server.properties
server/routes/main/index.js
server/routes/main/refresh.js
views/refresh.html

This is the page we will show when the preview in the editor needs a refresh. Should look like this...

Added a new "Reload preview" page.

---

public/editor/stylesheets/editor.less

Fixes #2469 Add scroll in Editor dropdown menu

---

server/routes/main/index.js

Allow CORS for editor on /refresh route

---

server/index.js
server/routes/config.js
server/routes/main/index.js
server/routes/main/refresh.js
server/security.js

Allow security headers to be overriden for individual routes

Allow security headers to be overriden for individual routes

---

.appveyor.yml
env.dist

This also removes a bunch of env vars we don't use anymore.

Appveyor and env cleanup

---

server/routes/main/features.js
server/routes/main/get-involved.js

Made changes suggested by @gideonthomas

Fixes #2102 - When switching locales, stay on the same page

---

package.json

Huge thanks to @humphd for helping me to use git for this is-reachable-fix. This is a continuation of issue #2520 to add is-reachable to package.json.

Added is-reachable to package.json

---

public/editor/scripts/ui/menus.js
views/editor/nav-options.html

Display font size
(On the clip, the letter "あ" shows up, I could not remove it, but it's my windows' bug)

Fix #2118: Feature Request > Indicate font size next to font size UI

---

package.json
server/request.js
services/login.webmaker.org/app/http/controllers/site.js

This is for fix #2181 using [git-rev-sync](https://github.com/kurttheviking/git-rev-sync-js) to record the current commit in /healthcheck.

update /healthcheck to note the build commit - Issue 2181

---

public/editor/scripts/ui/index.js

- Prevents preview icons from being dragged.
Closes #1966

Improve UX of clicking preview icons: Prevent drag

---

locales/en-US/editor.properties

In reference to [PR](https://github.com/mozilla/brackets/pull/916)

Added localized strings for inline Padding editor

---

locales/en-US/editor.properties

In reference to [PR](https://github.com/mozilla/brackets/pull/918)

Added localized strings for Margin Editor 

---

README.md

[docs] - mozilla/thimble.mozilla.org - README.md  - fixing tiny little issues (grammer, spelling, et. al)

---

locales/en-US/server.properties
public/homepage/scripts/glitch.js
public/homepage/scripts/main.js
public/homepage/stylesheets/glitch-notice.less
views/homepage/base.html
views/homepage/glitch-notice.html

Implements the homepage CTA as per, but does not yet close, https://github.com/mozilla/thimble.mozilla.org/issues/2656
- still needs the additional two screens from the comp

homepage CTA after 2 seconds

---

locales/en-US/server.properties
public/projects-list/scripts/glitch.js
public/projects-list/scripts/main.js
public/resources/stylesheets/glitch.less
server/routes/projects/read.js
views/projects-list/glitch-notice.html
views/projects-list/index.html
webpack.config.js

closed #2658
stubs out #2659 
I had to guess the styling for the "hooray!" line, but far as I can tell it looks near identical.
This also moves the .less file so that it's used by both homepage and project list, but duplicates the actual glitch template HTML because they're slightly different and given these are effectively final changes to Thimble, having a bit of duplication in the glitch-specific code feels fine?

Project list banner and export button stubs

---

locales/en-US/server.properties
public/editor/scripts/glitch.js
public/editor/scripts/main.js
public/editor/stylesheets/editor.less
public/homepage/scripts/glitch.js
public/homepage/stylesheets/style.less
public/projects-list/scripts/glitch.js
public/resources/stylesheets/glitch.less
public/resources/stylesheets/userbar.less
server/routes/main/editor.js
server/routes/main/features.js
server/routes/main/get-involved.js
server/routes/main/homepage.js
views/editor/glitch-notice.html
views/editor/index.html
views/editor/layout.html
views/homepage/glitch-notice.html
views/homepage/userbar.html
views/projects-list/index.html

based on b0841f6, which still needs to land.
closes https://github.com/mozilla/thimble.mozilla.org/issues/2666
closes https://github.com/mozilla/thimble.mozilla.org/issues/2667

Editor banner + cta

---

README.md

fix SetX Markdown link formatting in README.md

fix SetX link display in README.md

---

public/editor/scripts/glitch.js
public/projects-list/scripts/glitch.js
server/lib/middleware.js
server/routes/export/data.js
server/routes/export/finish.js
server/routes/export/index.js
server/routes/export/metadata.js
server/routes/export/start.js
server/routes/index.js
server/routes/utils.js

Add proxy routes for exporting projects
