mozilla/thimble.mozilla.org

routes/index.js
To test this, you can do:
* http://localhost:3500 (i.e., no query string).  Should load Bramble normally
* http://localhost:3500?enableExtensions=CodeFolding the CodeFolding extension should be on (little triangles next to collapsable bits of the html file)
* http://locahost:3500?ui=1 Should show the full Brackets UI
=> Fix #503 - Automatically pass query string params down to the editor iframe

app.js, bower.json, env.dist, lib/environment.js, lib/metrics.js, lib/middleware.js, lib/parameters.js, lib/proxy.js, package.json, public/friendlycode/js/require-config.js, public/scripts/ssooverride.js, routes/index.js, views/index.html, views/userbar.html
This is a full implementation of Thimble using the [id.webmaker.org](https://github.com/mozilla/id.webmaker.org) oauth2 server for authentication. Very little UX was changed since a refresh is in the works.
**Known issues:**
1.  Logging in will lose all work in the editor. 
2.  Toolbar links to "my profile", "my settings" and "my makes" won't work since the rest of wm.o isn't configured to use `id`. 
3.  Thimble must completely load before signing in is possible.
**Test instructions:**
1. Clone, install, configure and run [id.webmaker.org](https://github.com/mozilla/id.webmaker.org). You'll need to install and run postgres to make this work, and you'll need to create and populate the `webmaker_oauth_test` database. Copy [this sql in this gist](http://pastebin.com/mqSS9bnu) over the …
=> [WIP] Integrate ID into thimble

env.dist, public/stylesheets/userbar-overrides.less
Changed dist model for .env to provide only langs with 100% translation, override language box width to auto.
=> Only 100% translated langs, override lang picker width

lib/errorhandling.js, public/friendlycode/js/fc/load-project-files.js, public/friendlycode/js/fc/stay-calm/index.html, public/friendlycode/js/fc/stay-calm/style.css
I've also slipped in a minor fix to the error handling middleware we use, which was wrong before.
This temporarily overrides how we do the default project content so @flukeout can do user testing, see https://github.com/mozilla/thimble.webmaker.org/issues/558#issuecomment-117259560
=> Stay Calm template for user testing, minor fix to node error handling

public/friendlycode/css/editor.less, public/friendlycode/js/fc/bramble-ui-bridge.js, views/friendlycode/templates/nav-options.html
Fixed closing the menu when clicking outside, as per feedback by users on #649 
cc @humphd or @flukeout for r.
=> Added underlay for options menu, close menu on outside click

public/friendlycode/css/editor.less, public/friendlycode/js/fc/bramble-ui-bridge.js
This makes it so that clicking either theme option toggles the theme.  I've also updated the CSS pointer, which I remember reading you wanted somewhere (can't find bug).
=> Fix #650 - Make the entire editor theme toggle element clickable

public/scripts/editor/js/fc/bramble-keyhandler.js, public/scripts/editor/js/fc/project-rename.js
The event state becomes a bit trickier when you can click or press enter, so I have to do more work to manually add/remove event listeners, which makes the `project-rename.js` code a bit more complicated.
One thing I notice about this UX for another bug: there is no non-keyboard way to cancel a rename once you start.  I wonder if we should have a way to do "Save" or "Cancel" (checkmark and an x?).  cc @flukeout
=> Fix #711 - Enter and Esc keys should work on project rename field

public/scripts/editor/js/fc/bramble-ui-bridge.js, public/stylesheets/editor.less, views/nav-options.html
This is only a start, but it lets us really get a feel for things.  I still need a visual way to add the tutorial.html, but adding one manually (right-click in file tree, name your file `tutorial.html`) will have the right effect.
I keep track of whether or not there is a tutorial, and show/hide the TUTORIAL button accordingly.  I have to fix one bug in Bramble where deleting an active `tutorial.html` file leaves you in tutorial mode--it doesn't cause problems, but it's not right.  I'll file after this.
=> Initial UI for Thimble to use Bramble Tutorial feature, part of #573

lib/middleware.js
This was a quick patch meant to improve the UX of an unauthenticated user who tries to access a route meant for authenticated users. Imagine someone bookmarking the `/projects` page but their cookie expires. 
@flukeout I could follow this up with a patch that shows some UI informing the user about why they were redirected. Thoughts?
=> Fixed #734 - Added auto redirects to the home page 

public/scripts/editor/js/fc/bramble-ui-bridge.js
Testing steps:
1.  Publish a project
2.  Make changes
3.  Before it auto-saves, click "Publish"
It should quickly update to show the "Updated Published" button.
=> Fix #699 - Make publish dialog show 'update published...' button even if changes haven't been saved

public/scripts/project/metadata.js, public/scripts/project/project.js, public/scripts/project/remote.js
This wraps all read/write access to the project's metadata xattr in a lock, so we can safely parallelize file updates on the server, but queue them on the client.  It will fix https://github.com/mozilla/thimble.webmaker.org/issues/814.  This lock isn't safe across tabs, but I don't think we are going to support opening the same file across tabs?  If we want that, I just need to move the lock into a file vs. ram.
=> Lock access to project metadata xattr

public/resources/remix/style.less
The Remix button is sitting under the remix header, due to tag ordering.  This forces it to sit on top.
=> Bump z-index on remix button in published header

public/scripts/editor/js/fc/bramble-menus.js
This stops us from re-setting the theme on startup, when all we need to do is change the UI for the buttons.
=> Thimble portion of fix for #896, also requires https://github.com/humphd/brackets/pull/440

lib/middleware.js, public/stylesheets/userbar.less, views/layout.html, views/nav-options.html, views/publish.html
This gets rid of all the annoying CSP warnings.  All that's left are warnings about us being in report-only mode, which is fine.
=> Kill off CSP violations and reduce CSP warning spam on console

views/nav-options.html
This is my fault, I made a typo when I removed the inline style.  this fixes things on startup so it doesn't show the filetree.
=> Fix #924 - fix typo on filetree class markup to hide on startup

default/empty-project/index.html, default/empty-project/style.css, env.dist
I modified what you had in that bug slightly so that it forces HTML5 rendering vs Quirks Mode (doctype) and will render properly in mobile.
@sedge NOTE: we'll need an env update when this lands.
=> Fix #541 - create default empty project

public/editor/scripts/editor/js/bramble-editor.js
This depends on https://github.com/humphd/brackets/pull/426, and will silently try to deal with a failed filesystem.  I'm not doing an UI, but a refresh is the most likely outcome for the user.
=> Fix #861 - try to autorecover a corrupt filesystem

public/homepage/scripts/main.js
This overrides the default error handling in require and keeps it from throwing when we preload those Bramble modules, see http://requirejs.org/docs/api.html#errors
=> Don't spit out massive error when preloading editor modules on homepage

public/editor/scripts/editor/js/fc/bramble-popupmenu.js
This fixes two things:
* properly deals with unbinding the resize event so it doesn't fire forever after closing the popup
* deals with click events on the popup menu button that were being missed (saw this in user testing video).
=> Fix #932 - stop popup menu from throwing on resize, missing click events

public/homepage/scripts/main.js, views/homepage/index.html
This fixes how I was doing the pre-fetching of Bramble's largest assets.  This is going to need a CORS update to our staging and prod S3 buckets, in order to allow our various Thimble servers to xhr GET some files from the Bramble S3 bucket.  @jbuck, can you help with this, I followed http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html#how-do-i-enable-cors:
```xml
<CORSConfiguration>
<CORSRule>
<AllowedOrigin>https://bramble.mofostaging.net</AllowedOrigin>
<AllowedMethod>GET</AllowedMethod>
<AllowedHeader>*</AllowedHeader>
</CORSRule>
<CORSRule>
<AllowedOrigin>https://thimble-beta.webmaker.org</AllowedOrigin>
<AllowedMethod>GET</AllowedMethod>
<AllowedHeader>*</AllowedHeader>
</CORSRule>
<CORSRule>
<AllowedOrigin>https://thimble.mozilla.org</AllowedOrigin> …
```
=> Preload large Bramble assets on homepage in order to cache

app.js, package.json, public/editor/scripts/editor/js/bramble-editor.js, public/editor/scripts/main.js, public/editor/stylesheets/editor.less, routes/main/editor.js, views/editor/bramble.html
This is a start, we need proper UI from @flukeout.  I've added the `browser-support-warning` div and css to the `bramble.html` view.
=> Warn users with browsers that aren't known to work with Thimble

public/editor/scripts/editor/js/fc/bramble-ui-bridge.js, public/editor/stylesheets/editor.less
**Changes**
* Set the editor header column widths by pixels to avoid percentage rounding problems
* Changed the toolbar background to grey so there aren't flashes of white when things are resizing
Tested in FF and Chrome and performance is fine!
Fixes #1010
=> Editor heading bar updates - Fixes #1010

public/editor/stylesheets/editor.less, public/resources/img/icon/file-tray-arrow-left.svg, public/resources/img/icon/file-tray-arrow-right.svg
Changed the icons and style a bit so they appear the same in Firefox and Chrome.
Fixes #946
=> Updated file tray arrow icons - Fixes #946

public/editor/scripts/project/project.js
Seems like I introduced a regression with 224ddda. When we create a new project/remix a project as an authenticated user, we lose the project title. This PR makes it so that we check to see if we can get the project title from the project root, if not, we should use what the server sends us.
=> Fix regression - Show 'Untitled Project' when creating a new project as a signed in user

public/editor/scripts/editor/js/bramble-editor.js, views/editor/bramble.html
This builds on https://github.com/humphd/brackets/pull/455 and causes us to error when the user is in private browsing mode.  We no longer try to auto recover a failed indexeddb, and that's because we can't do that and warn.  I think the errors we're hearing about in the wild are not corruption, but rather private browsing mode in ff.  This should make things better, since they'll get some info instead of a loading screen that never ends.
=> Fix #1031: warn users of failed filesystem operations in private browsing mode

public/editor/scripts/main.js, routes/files/read/data.js
This switches our content-type for the project tarball to be something IE can handle (i.e., will decompress).  I've also fixed a load ordering bug in our error handling, where jquery wasn't in scope yet.  Finally, I adjusted the checks for browsers we don't support.  These are temporary, and we can remove them once the UI gets updated.
=> Fix #1064 - project TAR file gets corrupted, can't be parsed in IE

public/editor/scripts/editor/js/fc/bramble-input-field.js
We have 2 places where we deal with text from a user.  In one case it's always located in a `textarea`.  In the second, we let them type in an `input` and then get the content and put it in a `span`.  I've modified the code to do what @jbuck suggests, and use `textContent`.
=> Fix #1085 - sanitize text input in Thimble

public/editor/stylesheets/editor.less, public/resources/stylesheets/userbar.less
This fixes the column headers for IE, as shown here...
Tested in FF, Chrome & Safari as well.
Fixes #1079
=> Changes to make the column headers display properly in IE.

public/editor/scripts/main.js, views/editor/bramble.html
This removes the IE/Edge warning, and adjusts things to only warn for IE 10, etc. and earlier versions of Safari.
=> Remove warning for all modern browsers, warn for < IE 11 and < Safari 8

public/editor/scripts/sso-override.js
This tries to use Bramble, which may or may not be loaded (homepage vs. editor), and if it does exist, it calls `bramble.saveAll()` before allowing the user to navigate away and sign-in/up.
=> Fix #1119 - trigger bramble.saveAll() before navigating away for sign-in

package.json
Fixes #1128 on Windows but needs testing on other platforms (linux / osx)
=> Run grunt without a path in the postinstall script

public/resources/stylesheets/userbar.less
The UI elements no longer wrap to two lines when the header is squished. Also put a max-width on the project name display so it doesn't get out of hand.
Fixes #1082
=> Fixed header styling when it becomes narrow.

public/editor/scripts/editor/js/fc/bramble-popupmenu.js
There are two code paths where `self.close` can get called, only one of which has an event object that needs to be stopped from propagating.  This adds support for the manual call, with no event object.
=> Fix #1155 - support event based and manual closing the popup menu.

.travis.yml, invalidate.js, package.json
This patch adds automatic invalidation of the CloudFront edge caches for Thimble whenever we deploy to production
To be completed:
=> [WIP] Fixed #1132 - Invalidate CloudFront edge caches on a prod deployment

Gruntfile.js, bower.json, public/editor/scripts/constants.js, public/editor/scripts/editor/js/bramble-editor.js, public/editor/scripts/editor/js/fc/bramble-ui-bridge.js, public/editor/scripts/editor/js/fc/filesystem-sync.js, public/editor/scripts/editor/js/fc/project-rename.js, public/editor/scripts/editor/js/fc/publisher.js, public/editor/scripts/editor/js/fc/sync-manager.js, public/editor/scripts/editor/js/fc/sync-state.js, public/editor/scripts/logger.js, public/editor/scripts/main.js, public/editor/scripts/path-cache.js, public/editor/scripts/project/metadata.js, public/editor/scripts/project/project.js, public/editor/scripts/project/remote.js, public/homepage/scripts/main.js
This is untested, and not 100% complete.  But I think I'd like a review, since I didn't write any of the code I'm replacing.  I'm especially not sure about enabling/disabling the publish dialog.  I'm trying to move to using events instead of callbacks for the sync manager.  I can probably remove a bunch of stuff in that file, but I'm not sure yet.
=> Fix #1092 - store file sync state info in the project root xattrib

public/editor/scripts/editor/js/fc/bramble-input-field.js, public/editor/scripts/editor/js/fc/project-rename.js
This fixes a few bugs:
* we were adding/removing (and mostly adding) the click handler over and over when the any key handler ran.  Instead of doing this, I just add it once, then ignore it if the button is disabled when it fires
* I've fixed the esc key handling so that it restores the title as it was before editing began. This includes both the 0 length string case, and also all other cases.
* to fix the above, I had to fix a bug in the input field, where it wouldn't set the proper attribute on both an `input` and `span`.
Testing this now only gives me 1 request for both the `enter` case and also the `click` of the Save button.  I also find the esc key does what I expect.
@gideonthomas r?
=> Fix #1198 - Renaming the project triggers multiple requests

public/editor/scripts/editor/js/fc/bramble-menus.js, views/editor/nav-options.html
This adds UI to toggle automatic JS execution in the preview on/off.  We've had support for this in Bramble since the beginning, but never bothered to do UI.  I think it's pretty useful when you're doing large JS projects and want to block re-running JS on every refresh.
I'm not sure of the best wording: "Allow JavaScript" vs. "Autorun JavaScript" vs. ...?
NOTE: this is a runtime option vs. something we save in your overall preferences, since it's pretty specific to a particular project, and I think liable to confuse users if we disable it by default on startup.
r? @gideonthomas, @flukeout
=> Fix #1196 - add UI for enabling/disabling automatic JS execution in the preview

public/resources/remix/index.js, public/resources/remix/style.less
@flukeout, see if this is good enough for now, so we don't crowd out the page content on a mobile phone.
=> Hide published details bar when on mobile phones without enough room

public/resources/remix/index.js, public/resources/remix/style.less
I tested the fix on staging, and it's not quite right.  The padding won't get dealt with for small screens, because the check for the remix details bar being visibile is always going to return true, since the stylesheet will be loaded already.
This changes things to instead use the window width.  I've also fixed a bug that caused the wrong style to get applied to mobile screens in portrait.
=> Deal with remix stylesheet loading after padding on body already applied for remix bar

public/editor/scripts/constants.js, public/editor/scripts/editor/js/fc/backoff.js, public/editor/scripts/editor/js/fc/filesystem-sync.js, public/editor/scripts/editor/js/fc/project-rename.js, public/editor/scripts/editor/js/fc/sync-manager.js, public/editor/scripts/open-project.js, public/editor/scripts/project/metadata.js
This patch greatly improves our performance when the network or server go down, or when the server is under heavy load.  When an update or delete network operation fails, this adds some delay before retrying it.  Previously, we just tried again right away, and if the server was under load, we'd just do that over and over in a tight loop forever, which will kill the server with enough clients all doing it at once.
This also fixes a bug where we incorrectly thought we'd completed a sync if the server went down (i.e., `net::ERR_CONNECTION_REFUSED` vs. a `500` response).  This would mean that we could lose track of files that need to get synced in the event of a crashed server.
This also provides a bit of UI indication to the user when saving fails, letting them know and that it is being …
=> Fix #1241 - Stop Thimble (client) from DDoS'ing Thimble/Publish servers

public/editor/scripts/editor/js/fc/bramble-menus.js
This simplifies the code that figures out what we should do on startup, and forces bramble into the right state no matter what.  I can't reproduce the theme problem anymore with this patch.
r? @gideonthomas
=> Fix #975 - Thimble doesn't remember my theme settings

public/resources/remix/index.js
This adds GA tracking for published projects via the remix header injection.  Since we load this file without any processing (not templated), I just embedded the tracking id directly in the code.  I've also cleaned-up this file a bit to isolate things from the global scope.
=> Fix #1164 - Add GA tracking to Published projects

Gruntfile.js, public/editor/scripts/main.js, public/editor/scripts/open-project.js, public/homepage/scripts/main.js
If not instructed to do otherwise, requirejs will timeout module loading after 7s.  Based on similar bugs and fixes in other code, I've set our Thimble timeout to be 2 mins.  I'm going to do a similar fix in Bramble.
=> Don't crash when loading over low-bandwidth networks, part of #1224

public/resources/tutorial/tutorial.css
I originally added this to fix the styling of the steps list for when it has unrealistically short content, which never really happens. This removes that attempt which also clears some terrible unexpected results like in the bug listed below.
Fixes #1309
=> Removing flex rule for steps list to fix styling bugs.

Gruntfile.js, package.json, scripts/common.js, scripts/localize-client.js, scripts/properties2json.js
This patch does a couple of things:
* Uses a build script to create separate client files for each locale
* Adds a watch to update the built files when the source code changes
Note: This patch is more of a tool that will be used in the next patch rather than showing any obvious changes in the application.
Note 2: This should be landed after https://github.com/mozilla/thimble.webmaker.org/pull/1377
=> Client L10N Tools

views/homepage/index.html
Pontoon needs to be able to discover these text nodes and so we need to wrap them in container elements...I chose spans.
=> Wrap homepage footer elements in spans for discoverability by Pontoon

.travis.yml, scripts/localize-brackets.sh
This step will run every time a Travis build occurs and will check to see if the commit being built is a string change to the Brackets' string files. If it is, it triggers a rebuild on Brackets (which would pull the string changes and update the repo - writing code for that now).
One thing I'm not so sure of is the API token that I use in the travis request. I generated that locally using `travis login && travis token` according to https://docs.travis-ci.com/user/triggering-builds but I don't know if that is only for a session (would need to be regenerated every time) or should work for this case.
=> Add script to trigger build on Brackets for new strings

public/resources/remix/style.less, views/project-remix-bar.html
created commit for issue 1381 - https://github.com/mozilla/thimble.mozilla.org/issues/1381 - 
removed remix button when printing page in published preview - by adding print style to css/less.
=> Updated style.less to remove remix bar when printing and open remix in new tab feature

public/editor/stylesheets/editor.less
I tried playing with the sizing, and doubling things fixes it.  The problem is the extra width of the newly added `auto` checkbox for refresh.
r? @flukeout, @gideonthomas
=> Fix #1474 - Disable Fullscreen Button is not working

public/editor/scripts/constants.js, public/editor/scripts/editor/js/fc/filesystem-sync.js, public/editor/scripts/editor/js/fc/publisher.js, public/editor/scripts/editor/js/fc/sync-manager.js, public/editor/scripts/path-cache.js, public/editor/scripts/project/project.js, server/routes/projects/index.js, server/routes/projects/rename-folder.js
This is one part of a 3 part fix. The other two parts need to happen in publish.wm.org and brackets respectively. Here is the link to the Brackets PR - https://github.com/mozilla/brackets/pull/558.
This patch is blocked on the publish.wm.org patch landing first which will add a route to deal with folder renames.
The main purpose of this PR is to distinguish folder renames from file renames and handle them differently. The following changes have been made:
* A folder rename event will be listened for
* The path cache will be updated with a new folder rename entry which will have information about the old path, the new path, and all the file paths (stored as relative paths) contained in that folder that were affected by the rename (their abs paths have changed)
* The format of the path …
=> Fix #1311 - Renaming folders will no longer cause saving failed errors

public/resources/stylesheets/userbar.less, views/editor/userbar.html
Added margin to the right of the icon to space it from the text.
See Issue #1480 
First commit, Woo!
=> Fix spacing between publish icon and publish text

public/editor/stylesheets/editor.less
Closes #1427. Fixes the overlapping text/inputs on the editor options menu by removing the `min-width` and replacing it with padding large enough for the option toggles.
=> Fix overlapping text/inputs in options menu.

.gitignore, README.md, Vagrantfile, scripts/sql/oauth-setup.sql, scripts/start-services.sh
Follow the instructions from the readme changes in this PR to see if you can setup Thimble.
Needs to be tested on Windows.
=> Fix #1604 - Use vagrant to run Thimble + all services

server/localize.js
URL redirects were being concatenated as if they were filenames, rather than being URL strings. These are two completely unrelated things, and the assumption broke the code on all OS that don't use `/` as standard path separator. This patch ensures that the URL is written correctly.
=> fix locale redirection due to joining as filename

server/localize.js
Safe way to handle slashes while forming the url during localization
=> Fix #1691 - Handle extra slashes in url construction during localization

public/resources/stylesheets/userbar.less
**:after** Pseudo-elements were added to userbar.less. This solved the top-edge issue. I followed https://css-tricks.com/video-screencasts/123-if-it-moves-when-you-click-make-something-stick/ as a guide.
You can hopefully see what I did here: http://codepen.io/cgsingh/pen/JEpBgL.
=> Fix #1534 - Publish button clicking

public/editor/scripts/editor/js/fc/bramble-ui-bridge.js, views/editor/publish.html
Just added id tag in publish.html and a click event to the link in bramble-ui-bridge.js like @gideonthomas suggested to someone else who no longer wanted to work on this issue.
Fixes #1333
=> Fix #1333 - Dismisses Publish Dialog when link to Published project is clicked

public/resources/stylesheets/userbar.less
This resolve #1635  the issue found [here](https://github.com/mozilla/thimble.mozilla.org/issues/1635) which made the clickable padding of the logged in user menu not register. To remedy, I increased the padding of the link itself and decreased the padding of the `<li>` element which surrounded it.
=> Fix #1635 - Fixed logged in user dropdown menu easier to click

public/editor/scripts/editor/js/fc/bramble-menus.js
To fix this bug, we still need to modify the files on brackets.
Here is the brackets pull request.
https://github.com/mozilla/brackets/pull/584
=> Issue1631- remember allow javaScript setting

public/editor/scripts/project-list.js, public/editor/stylesheets/projects-style.less, server/routes/projects/read.js, views/editor/projects.html
Now users should be able to open a project in a new tab.
In addition, since we use a regular link now, I see no point in keeping this [listener](https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/project-list.js#L37-L39).  Let me know please whether I am right.
=> Fix #1627: Added ability to open a project in a new tab

public/editor/scripts/editor/js/fc/bramble-ui-bridge.js, public/editor/stylesheets/editor.less, views/editor/nav-options.html
This feature makes the UI in each of the header bars (file, editor and preview) adapt to the available amount of space.
It works by measuring the available space and seeing if there is enough room for all of the elements. If there isn't, it looks for elements with an ``adapt-priority`` attribute, and one by one, adds a ``.narrow`` class to them, which changes their styling or hides them entirely.
It looks something like this...
Fixes #1753
=> Responsive UI in pane headers

public/editor/stylesheets/projects-style.less, views/editor/projects.html
Let me know if I should change anything. I made sure the "Delete" <td> was centered, otherwise it looked weird positioned below everything, especially in comparison to a project that didn't have a description.
=> Issue #1755 - Your Projects Page shows Project Descriptions

Vagrantfile
This stops us from forwarding the postgres port out of the VM, so that it won't conflict with services running in the host.
I tested it locally, and it still runs fine for me.  I'm not sure if it will fix Pomax's issue.
=> Don't leak port 5432 from Vagrant VM into host, part of #1764

public/editor/scripts/editor/js/fc/bramble-ui-bridge.js
I added some code to handle issue #1633 to the bramble-ui-bridge.js file. The back end for this is https://github.com/mozilla/brackets/pull/595.
This code just does the front end part, checking on load to see the preference stored for autoUpdate and changing the .refreshwrapper element to reflect that (by removing the checkmark if needed).
Final testing has yet to be done and will be done once the back end has been finalized as well.
=> added front end support for auto update preference to fix issue #1633

env.dist
=> Remix projects redirect to dead URL on local Thimble setup

public/editor/scripts/editor/js/fc/project-rename.js, public/editor/scripts/main.js
I have fixed the issue. Now the title appears for anonymous projects. 
Let me know, please, if you have any questions or you would like to change something. 
Thank you very much!
=> Fix #1747: Project title appears on editor header for anonymous projects

server/routes/auth/oauth2-callback.js
In reference to  #1760 
Simply removes the code that redirected to the home page in case a user came from the same.
=> Redirects the user to his projects page after he signs in from the home page.

ecosystem.json, server/templatize.js
With this fix, you now only need to refresh the browser to see new HTML changes while running thimble on your local machine, instead of the old way by restarting your server.
**Old version:**
` let engine = new Nunjucks.Environment(paths.map(path => new Nunjucks.FileSystemLoader(path)), { autoescape: true });`
**New Version:**
` let engine = new Nunjucks.Environment(paths.map(path => new Nunjucks.FileSystemLoader(path, { noCache: true, watch: true } )), { autoescape: true });`
=> Fixed Issue #1397 No longer need to restart server to see new html changes while running thimble on your local machine

server/lib/environment.js
Here is the fix of the issue that happens with [deps update](https://github.com/mozilla/thimble.mozilla.org/pull/1828). 
This request updates deps, and the newest version of jshint, treats this code as an error, instead of just as a warning. 
```js
var habitat = require('habitat');
habitat.load(require('path').resolve(__dirname, '../../.env'));
var env = new habitat();
```
There is anything wrong with this code. That's why the easist solution to pass new updates of jhint, is to supress the warning. In addition, this syntax check will be deprecated in the next version of jshint.
=> Fix #1829: Added warning supression for new versions of jshint

server/security.js
Tested locally on Firefox, and this allows the `.zip` download to happen.
=> Fix #1595: allow blob: URLs in CSP to download zip files from editor iframe

locales/en-GB/messages.properties, locales/en-US/messages.properties, views/editor/bramble.html
Added errorLoadingProjectBramble error message to messages.properties
Added errorLoadingProjectBramble error to bramble.html
I saw that the error message already existed and showed in developers tools console.
I added a error message that tells the user to look in their browsers developer tools console to see error details.  
This will make is so that developers know if bramble is the cause of the error right away alongside of any other errors they might not have known about. 
Here is a picture of the dev tool error message.
https://gyazo.com/e1a4ffbbe37a11aaf8200c8273327a77
fixes #1758
=> Added extra error message for developer troubleshooting

server/index.js
In https://github.com/mozilla/thimble.mozilla.org/commit/20fa70c77fb6a9dbdad29492989715178954fada we started using `node_modules` vs. front-end resources installed via bowser.  Then, in https://github.com/mozilla/thimble.mozilla.org/pull/1808 we started having nunjucks watch for template changes in the directories it used.  The combination of these two things meant that we started watching `node_modules` which causes the Vagrant VM to run out of space as it tries to watch all the files under `node_modules/*`.  On my machine Thimble takes forever to start, and then I get errors like this:
```
4|thimble  | Watcher error: Error: watch node_modules/grunt-lesslint/node_modules/less/test/less/errors/property-in-root.txt ENOSPC
4|thimble  | Watcher error: Error: watch …
```
=> Fix ENOSPC errors watching node_modules, don't pass node_modules to nunjucks

public/homepage/stylesheets/gallery.less
Here is the fix for the hover state. 
I have just used the same technique that was used for hovering tag buttons on the homepage (by changing the opacity of buttons). 
Here is how it looks: 
Fixes #1956
=> Fix #1956: Added hover state to Homepage Gallery Remix Button

Gruntfile.js, package.json, public/editor/scripts/analytics.js, public/editor/scripts/editor/js/fc/bramble-menus.js, public/editor/scripts/editor/js/fc/bramble-ui-bridge.js, public/editor/scripts/editor/js/fc/project-rename.js, public/editor/scripts/main.js, public/editor/scripts/project-list.js, public/homepage/scripts/gallery.js, public/homepage/scripts/main.js
Fixes #1794 
**Changes**
* Ripped out the ``webmaker-analytics`` node module and put the code into ``public/editor/analytics.js`` instead
* Removed Optimizely references from the analytics code
* Removed the Fallback old way of doing Events
* Rewrote all events to have separate cateogries
* Linked events to UI actions
* We only count a theme toggle when the user does it explicitly, not when we set it on refresh
* Paired events together so there is a "Enabled" and "Disabled" label with the same action like "Toggle Javascript"
* Added some analytics events to the new homepage Gallery
I think that's it - can I get a look-over @humphd
=> Update to Google Analytics

package.json
I have updated the jquery dependency
I tested using "npm install" and all seems to work fine from my end
=> Fix #1908: Issue 1908 jquery update

public/resources/stylesheets/userbar.less
Is this okay? I have it extend just above the green portion of the page.
=> Fix #1962: Scrollable Language Menu

public/editor/scripts/editor/js/fc/bramble-ui-bridge.js
The old implementation waits 200ms after adapting the layout before it calls the adapt method again. A lot can happen in that 200ms, so we want to also make sure we call it once after the last UI resize.
This feels a bit janky @Pomax so I'm curious about your thoughts.
The goal is to call the adapt method frequently, but not more often than 200ms, while also calling it one last time at the end.
To test this, resize the windows quickly - the icons should always adapt.
=> Makes sure the adapt method gets called after resizing

public/editor/scripts/project/project.js
I tried to "ask" Bramble to create the index.html file once it's ready. For this fix, the following message will still shows up when there was no index.html file previously:
I also have a different fix that looks something like this:
````
var file = getRoot() + "/index.html";
fs.writeFile(file, data, function(err) {
if (err) {
return console.error("Cannot write file to project: " + err);
}
});
````
This is obviously simpler and probably won't produce the above message. However, I'm not sure why I cannot declare `var fs = require("fs");` in [this file](https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/project/project.js#L2). This is the error message on the browser console:
````
GET http://localhost:3500/en-US/en_US/editor/scripts/editor/js/fs.js 404 (Not …
```
=> Fix Issue#1778: Create a default index.html file if there isn't one when the browser refreshes

public/editor/scripts/project-list.js
fixes issue number #1948 
Removed project.hide() in project-list.js and replaced it with project.fadeOut().
The slide-to-left animation before a project was deleted was unwanted and a fade out effect was preferred.
=> Fixes #1948, Remove strange effect on items deleted from Your Projects list

public/editor/scripts/editor/js/fc/sync-manager.js, public/editor/scripts/logger.js
I can't reproduce the bug the user had in #2018, but I think this a good start toward making things better.  The bug is that we have a pending file path to sync, but when we go to read the file from the local fs, it isn't there.  Here I check to see if we've hit an `ENOENT` while trying to read the current path in an update operation, and if so, I allow the sync operation to complete.  What happens now is that we fail forever, as we retry to sync the path, which is never there.
I don't think there are other cases for delete/rename that need this same treatment, but please look over the code and see if you agree.  I also can't think of other error cases we should treat this way for `readFile`, but maybe there are some I'm missing?
I've also added a console log to tell people how to get …
=> Fix #2018: Don't keep sync pending if local file vanishes during update

public/editor/stylesheets/projects-style.less
To test, load up the ``/projects`` view ("Your Projects") and test that when the browser window is too short to accommodate all of your projects, the page will scroll.
Fixes #2044
=> The project list now scrolls when it should.

locales/en-US/messages.properties, public/editor/scripts/analytics.js, public/editor/scripts/main.js, views/editor/bramble.html
This patch adds the following message to the loading screen...
It should appear after 10 seconds if the project hasn't loaded. For testing, you can make it appear faster by modifying ``var errorMessageTimeoutMS = 10000;`` [in this file](https://github.com/mozilla/thimble.mozilla.org/compare/master...flukeout:loading-screen-message?expand=1#diff-270f212d36b8a2447fd4f97c986a0b06R55)
cc @humphd
=> "Won't load" help message on green loading screen.

public/editor/stylesheets/projects-style.less
Some minor tweaks...
* Better padding in button
* Better garbage icon placement
* Reduced spacing between Delete and New Project button
* Moved shard styles into a mixin
cc @humphd 
Now looks like...
Super minor changes so might not even be noticeable to the untrained eye!
=> Project page button styling updates

Gruntfile.js, public/editor/scripts/bramble-shim.js, public/editor/scripts/editor/js/bramble-editor.js, public/editor/scripts/main.js
I have a few bugs in Thimble and Brackets (e.g., #1931) where I'm worrying about startup issues when the Bramble API we have in the Service Worker cache is not the same as what Thimble expects, specifically, when Thimble tries to use some new API call that isn't there in Bramble, and it just crashes and halts startup.  We've improved this a bunch with a couple of fixes to show "reload" buttons; but it still means we might crash, and a user who used to have a working Thimble suddenly doesn't.  That's what I'm most worried about with us launching all this new code.
This PR tries to mitigate that risk by providing default, shimmed versions of new APIs.  We will still want users to update, or some new features won't work fully; but at least we won't crash on startup, and we'll show the new …
=> Don't crash on load when Thimble expects newer Bramble API

views/homepage/userbar.html
They were always going to `en-US` otherwise, even if you selected a different language on the homepage.
=> Homepage nav items should open their localized pages

public/homepage/stylesheets/features.less
Layout now accommodates very long feature descriptions without breaking the layout, as seen below. Tested in FF, Chrome & IE 11 via Browser Stack.
Fixes #2098
=> Updated features page layout to accommodate long descriptions.

server/index.js, server/lib/http-error.js
Changes our `mozillaThimble` cookie to expire after 1 week vs. never, and forces sessions to get destroyed when we hit 500s, in the hopes of avoiding the case where user cookies are blocking a request from proceeding.
=> Expire session on 500s, only keep cookies for 1 week

server/index.js
this binds the maxAge to the express session, rather than the cookie parser
=> move maxAge into the session options

env.dist, server/lib/middleware.js
This adds the ability to assert that a user's session token exists, is a string, and is of the proper form.  If those aren't true, we log it.  I am not logging the actual token, only the characters that are outside what we expect.
cc @cadecairos, @Pomax
=> Temporary token assert code to figure out what's breaking on prod

public/homepage/scripts/getinvolved.js, views/homepage/get-involved.html
Since the API returns a max of 30 results. I've changed it to say "30+" when it equals 30 or more. This will be wrong in the case of there being 30 issues, but otherwise OK.
Fixes #2135
=> Adjusted the github issue count logic

server/lib/http-error.js
I notice that we aren't passing all the necessary variables to the `error.html` template when we show a 404 error vs. what we do on 500s.
=> Pass all necessary variables to error.html template for 404s

public/editor/scripts/editor/js/fc/bramble-menus.js, public/editor/scripts/editor/js/fc/bramble-ui-bridge.js, views/editor/userbar.html
This undoes some of what we did in https://github.com/mozilla/thimble.mozilla.org/commit/adf9a5f79f7828e2b025cc673c412dff823d2928 in order to duplicate the "Export .zip" feature, since users are confused by us moving it, and thinking we killed it off.  I think it's better to have it in both places.  I've also fixed the bug where we don't close the popup menu when we download the zip #2115.
Later in #2162 we might do something different again.  This is a stop-gap until then.
=> Duplicate Export to .zip feature to avoid confusing users, fixes #2115

public/editor/scripts/bramble-shim.js, public/editor/scripts/editor/js/fc/bramble-menus.js
Fix for crash reported by user:
I was returning the wrong type in the BrambleShim code.  The real answer is for the user to update to the new Bramble API, but this will stop us from crashing, and let the "Reload Now" flow work.
=> Return proper object type for bramble.getAutoCloseTags() shim, don't crash

locales/en-US/editor.properties
When we did https://github.com/mozilla/brackets/commit/413d7ce321b78e30cbf6124b0087ee15dfb41319 in Brackets, we forgot to land the string here.  This adds it.
=> Fix #2121: Add missing l10n string for console hint text

locales/en-US/messages.properties, public/editor/scripts/editor/js/fc/bramble-menus.js, views/editor/nav-options.html
This adds a new menu option above the file tree to enable adding folders.
I also wrote https://github.com/mozilla/brackets/pull/767 on the Brackets side to fix an issue in the naming of our commands, and we should land that first.
=> Fix #2072 - make it possible to add new folders from Thimble

views/error.html
This should fix the logo link and also cleans up the code a bit.
=> Fix #2163 - Missing locale variable breaks links on 404 page

public/editor/scripts/analytics.js, public/editor/scripts/editor/js/bramble-editor.js, public/editor/scripts/editor/js/fc/bramble-ui-bridge.js, public/editor/scripts/editor/js/fc/startup.js, public/editor/scripts/main.js
I notice that we can include timing and exception analytics in GA along with event categories.  I've expanded the API and added some new tracking code to help us see what's happening.
Fixes #2212
=> Expand GA analytics to include timing and exception tracking

public/editor/scripts/editor/js/fc/bramble-ui-bridge.js
This stops the panel resizing and UI adapting code from firing when we are in fullscreen mode when it's not needed. The related changes in the brackets PR below also ensure that when you exit fullscreen mode (and if you've changed the browser window size while in fullscreen) all of top bars above the editor panes are the proper size.
To know that this patch is working correctly:
* Open a project
* Enter fullscreen preview mode
* Resize the browser window
* **Check that** - the "Reload" icon doesn't disappear
* Exit fullscreen mode
* **Check that** - the UI bars above the editor panels are the correct size
Fixes #2226 when paired with https://github.com/mozilla/brackets/pull/775
=> Updating fullscreen layout code

public/editor/scripts/editor/js/fc/bramble-ui-bridge.js, public/editor/stylesheets/editor.less, views/editor/bramble.html, views/editor/userbar.html
This update adds a black overlay over the rest of the Thimble UI when brackets opens a modal dialog, like this...
It relies on two new brackets events...
* ``dialogOpened``
* ``dialogClosed``
...which are in https://github.com/mozilla/brackets/pull/778
=> Added an overlay when modals are open

views/editor/bramble.html
Commented out the error warning. To test, load up a new project and on the green loading screen, there will be no warning message.
=> Commented out the Warning message

public/resources/remix/index.js
This will track the ID of any project that is remixed via the Details Bar in Google Analytics.
Tested and shows up like this...
Fixes #2224
I'm not sure how to fix the last two remaining lints @gideonthomas
=> Adds GA event tracking when published project is remixed.

public/homepage/scripts/main.js, views/homepage/base.html
Finishing work started by @evantsyferov in #2013 and @Mordax in #2008.  This removes the hacked preloading of Bramble's large assets, and uses [<link> prefetching](https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ) instead.
The effect is the same, but this is a lot cleaner, and it also lets us get the `index.html` cached early for the editor too.
=> Fix #1991, #1524: prefetch bramble resources using HTML5 <link>s vs. script

public/editor/stylesheets/publish.less
Fixes a bug introduced in a previous PR that kept the Publish & Cancel buttons visible even after a project has been published.
To test...
* Publish a project
* Once published, the Publish & Cancel buttons on the dialog should disappear
Dialog should look like this (again)...
Fixes #2253
=> Fixed a bug that keeps the Publish button visible after publishing

server/security.js
@gideonthomas Fixes #2196 
I rehashed the spinner inline style and applied it as the CSP rule. I also removed the previously commented out hash, and the 'unsafe-inline' directive.
=> Fix #2196: Rehash inline style for spinner - style src CSP header

ecosystem.json
Other part of this is in https://github.com/mozilla/publish.webmaker.org/issues/250.
=> Fix #2014: add http:// protocol to PUBLIC_PROJECT_ENDPOINT

public/editor/scripts/project-list.js, public/editor/stylesheets/projects-style.less, public/editor/stylesheets/publish.less, public/homepage/scripts/gallery.js, public/homepage/stylesheets/gallery.less, public/resources/img/icon/snippets.svg, views/gallery.html
* Corrected styling for Delete Button on Your Projects page
* Changes the visual style of how items are removed from the Your Projects page
* Titles on the homepage gallery project cards are now clickable and go to the published version of those projects
* Updated .svg file for the snippet menu icon so that it renders correctly in Firefox
* Fixes bad styling on the Update Published button that caused the contents below it to shift slightly when the button was clicked.
Fixes #2309
Fixes #2284 
Fixes #2277
=> Small UI Fixes

ecosystem.json, env.dist, locales/fr/messages.properties, locales/it/messages.properties, public/editor/scripts/project/metadata.js, public/editor/scripts/project/project.js, public/editor/scripts/project/remote.js, server/routes/config.js, server/routes/files/index.js, server/routes/files/read/data.js, server/routes/files/read/file.js, server/routes/files/read/index.js, server/routes/main/editor.js, server/routes/utils.js
This alters the Thimble client and server to allow for a project to be loaded either as a tarball, or as a set of separate files.  I'm doing this behind an opt-in flag, because I want to experiment with it.  I'm curious to see what will happen if we remove the tarball creation from publish.  It is not fully optimized (e.g., I would need to modify publish to send `Buffer` vs. JSON), but that shouldn't matter too much.
To make this work, I've changed the project load order to load the metadata first.  This gives the file IDs if I need them for loading an expanded set of files.
To use it, add `?loadfiles=1` to the Thimble URL.  If you do nothing, it should load the project as a tarball like normal.
=> Allow loading projects as either a single tarball (default) or expanded files

Gruntfile.js, package.json, public/homepage/scripts/features.js, public/homepage/scripts/gallery.js, public/homepage/scripts/getinvolved.js, public/homepage/scripts/main.js, public/lib/keyhandler.js, public/lib/popupmenu.js, public/lib/underlay.js, scripts/localize-client-webpack.js, scripts/localize-client.js, scripts/start.js, views/homepage/base.html, webpack.config.js
This patch is the first step in adding webpack to Thimble and switching away from requirejs and grunt.
1. **Gruntfile.js** - Removes all the homepage scripts from the requirejs build step
2. **package.json** - Adds webpack and the npm scripts to run them
3. **public/homepage/scripts/(gallery | features | getinvolved).js** - None of the code has changed here. The only change made is to convert the require calls to CommonJS. It appears as a huge change due to indentation changes.
4. **public/homepage/scripts/main.js** - Requirejs config removed. Everything converted to commonjs. Removed passing around the modules via functions since they are required in.
5. **public/lib/(keyhandler | popupmenu | underlay).js** - These are identical copies to the files in …
=> Add webpack and convert homepage scripts to CommonJS

locales/en-US/editor.properties
These strings are needed for the change in https://github.com/mozilla/brackets/pull/847
=> Add strings needed by Brackets for https://github.com/mozilla/brackets/pull/847

locales/en-US/editor.properties
For https://github.com/mozilla/thimble.mozilla.org/issues/2331 I'm removing these strings, since we don't know the name of the file when we import and unzip.
=> Remove unneeded strings for unzip/untar

views/mozfest.html
One of our localizers noticed the error, this should fix it
=> Fix a hardcoded string in MozFest banner

Gruntfile.js, public/editor/scripts/editor/js/fc/bramble-menus.js, public/homepage/scripts/main.js, public/projects-list/scripts/main.js, public/shared/scripts/constants.js, public/shared/scripts/userbar.js, scripts/localize-client-webpack.js, views/projects-list/index.html, webpack.config.js
Relies on https://github.com/mozilla/thimble.mozilla.org/pull/2398 being reviewed and landed first.
This does basically the same thing as the previous webpack patch - this time for projects-list.
I didn't really make any code changes other than hoisting some of the variables that were global inside the require module to now being global inside the commonjs module.
I also moved the userbar popup creation logic (which is duplicated in all three modules - homepage, editor and projects-list) into its own module in `shared`. I added a note inside the editor module to switch to using that instead (because right now you can't include the commonjs module inside requirejs without some crazy shims) so that I don't forget to do it when I webpack editor.
=> Webpack projects list

.gitignore, .travis.yml, README.md, Vagrantfile, ecosystem.json, package.json, scripts/setup-services.sh, scripts/start-services.sh, server/index.js
This patch updates the node version to 8 and also removes Thimble out of Vagrant to make dev easier (yay no more breakable watch scripts).
You'll need to run this with Vagrant as per the Readme instructions. Would be good to test out on Windows as well.
=> Move thimble out of vagrant and use Node 6

public/editor/scripts/editor/js/fc/publisher.js, views/editor/publish.html
Fixes issue #2453 [here](https://github.com/mozilla/thimble.mozilla.org/issues/2453).  It makes clicking on the publish link open in a new tab.
=> Makes publish link open in new tab. Fixes #2453

public/resources/stylesheets/error.less, views/sign-out.html
This adds the correct styling to the Sign Out page. It can be viewed by following the steps to reproduce in #2450 and should appear now like this...
Fixes #2450
=> Fixed styling of the Sign Out error page.

locales/en-US/editor.properties
@flukeout 
Added locale string to "locales/en-US/editor.properties" for PDF Viewer title corresponding to changes done in brackets.
=>  Fixes #2378 : Added locale string for PDF Viewer Title 

package.json, public/resources/remix/index.js, webpack.config.js
The styles were missing in the remix bar for the published projects. It's because we weren't building the remix less file. This does that.
=> Fix missing styles in remix bar w.r.t. webpack

public/resources/scripts/error.js, views/refresh.html
We have a 404 when trying to load the `/refresh` route, which this fixes.  Also, this does the reload on the top-level iframe vs. the current window, which we'll need in Brackets.
=> Fix 404 on /refresh route, force top-level frame to reload

server/routes/main/refresh.js, views/refresh.html
Sets the origin to resolve absolute/relative paths in the html.
Includes the strings that are needed in the error.js file.
=> Set base for refresh and include strings

scripts/localize/index.js
Fixes #2499 - en-GB shows greek strings.
`Object.assign` apparently also assigns to the first parameter along with returning the assigned result (yay javascript :unamused:). This meant we kept reassigning the english strings with strings from other locales. By creating a new object literal every time, we ensure that there is no overwriting of objects that we need.
=> Fix #2499 - Fix fallback for missing strings in l10n script

README.md
`npm run env` requires `shx` so the `npm run install` step needs to be run prior to it
=> Fix order of env and install steps

public/homepage/stylesheets/style.less
If you resize the browser window while on the home screen, elements such as the video, and footer will begin to overflow.
I simply added a `max-width: 981px;` to the body tag in public/homepage/stylesheets/style.less
=> Fixing #2518: Added a min-width to the homepage body to prevent content overflow

locales/en-US/server-client-shared.properties, locales/en-US/server.properties, package.json, public/editor/scripts/ui/publisher.js
Fixes #1918 
The original issue was that the publish popup title would always display **"Publish your Project"** regards if it was live or not.
@flukeout @humphd My solution was to reuse the existing `h1`  in "_views/editor/publish.html_" to assign the value depending on the current state of the project performed on the server side. 
Unpublished title = **"Publish your Project"**  
Published title = **" Your Project is Online"**   
1. created var `TEXT_PUBLISHED_HEADER = strings.get("publishedHeader");` holds the string value from 
_"locales/en-US/server.properties"_
2. added publishHeader to the Publisher() object in "\public\editor\scripts\ui\publisher.js". This gets the `<h1>` id in _"views/editor/publish.html"_
3.  `Publisher.prototype.updateDialog` located in …
=> Update publish popup title when project is live - Issue 1918 

package.json, scripts/localize/index.js, server/lib/middleware.js, server/routes/auth/oauth2-callback.js, server/routes/files/create-update.js, server/routes/files/delete.js, server/routes/projects/rename-folder.js, server/routes/utils.js
I updated prettier and changed it to a ~ range instead of carat so that we only get patch versions since their minor version updates seem to break stuff.
=> Update prettier to tilde range

locales/en-US/server.properties, public/editor/scripts/ui/index.js, public/editor/scripts/ui/publisher.js, public/editor/stylesheets/publish.less, views/editor/publish.html
As a continuation of issue #2355 this allows the no index.html message to show when updating a publish. 
Mainly with jQuery I show `#publish-buttons` then remove the publish and cancel buttons to avoid having two publish buttons (update published version and publish).
=> Fixes issue #2355, adds no index message when updating project without index.html

package.json, server/request.js
This reverts commit 42f69f7654c0d7c8fee644ae52e2f9cae7246be4.
Unfortunately, as I suspected, Heroku doesn't guarantee a git repository and so `git-rev-sync` fails. I'll try to come up with a better solution and file a follow-up issue.
=> Fix #2577 - Revert "Update /healthcheck"

locales/en-US/server.properties, public/homepage/stylesheets/style.less, views/homepage/index.html
Closes https://github.com/mozilla/thimble.mozilla.org/issues/2702 by adding a new section right after the above-the-fold text+video+start, detailing that we'd like people to start using Glitch instead.
This PR comes with two new locale strings.
=> Main glitch notice
